# Introduction to Data Analytics Coding (Session 3)

In [34]:
import pandas as pd

### 1. Import the demo data (Current Applications) with only the first 2000 rows to (df)

In [35]:
df = pd.read_excel("/content/2425MBD41_Demo_Data.xlsx", sheet_name= "Current Applications", nrows=2000)
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,NAME_EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
0,267142,0,Cash loans,F,49500.0,473760.0,Secondary / secondary special,-23768,NaN,XNA
1,344230,0,Revolving loans,F,103500.0,180000.0,Incomplete higher,-10346,Core staff,Business Entity Type 3
2,205422,0,Cash loans,M,202500.0,904608.0,Secondary / secondary special,-19321,Drivers,Self-employed
3,103524,0,Cash loans,M,112500.0,220500.0,Secondary / secondary special,-14489,Laborers,Other
4,196457,0,Cash loans,M,112500.0,454500.0,Secondary / secondary special,-10423,NaN,Mobile
...,...,...,...,...,...,...,...,...,...,...
1995,442960,0,Cash loans,M,292500.0,1339884.0,Incomplete higher,-12627,Laborers,Business Entity Type 3
1996,318936,0,Cash loans,F,135000.0,111384.0,Secondary / secondary special,-17056,Laborers,Self-employed
1997,152503,0,Cash loans,M,112500.0,225000.0,Secondary / secondary special,-19457,Core staff,School
1998,285438,0,Cash loans,M,180000.0,640080.0,Secondary / secondary special,-10887,Laborers,Self-employed
1999,189812,0,Cash loans,F,450000.0,1288350.0,Secondary / secondary special,-21893,NaN,XNA

### 2. Show a summary table of the data (including both numerical and categorical variables)

In [36]:
df.describe(include="all")
#Here we have all the data in its aspect

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,NAME_EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
count,2000.000000,2000.00000,2000,2000,2000.00000,2.000000e+03,2000,2000.000000,1362,2000
unique,NaN,NaN,2,2,NaN,NaN,5,NaN,18,54
top,NaN,NaN,Cash loans,F,NaN,NaN,Secondary / secondary special,NaN,Laborers,Business Entity Type 3
freq,NaN,NaN,1810,1291,NaN,NaN,1398,NaN,385,439
mean,274816.122500,0.08150,NaN,NaN,169100.73225,6.061267e+05,NaN,-16017.907500,NaN,NaN
std,103651.070469,0.27367,NaN,NaN,92687.80762,4.077105e+05,NaN,4408.058808,NaN,NaN
min,100004.000000,0.00000,NaN,NaN,27000.00000,4.500000e+04,NaN,-25161.000000,NaN,NaN
25%,185056.250000,0.00000,NaN,NaN,112500.00000,2.700000e+05,NaN,-19589.500000,NaN,NaN
50%,270991.500000,0.00000,NaN,NaN,144000.00000,5.212800e+05,NaN,-15662.000000,NaN,NaN
75%,367201.500000,0.00000,NaN,NaN,202500.00000,8.353800e+05,NaN,-12323.750000,NaN,NaN
max,455877.000000,1.00000,NaN,NaN,900000.00000,2.517300e+06,NaN,-7769.000000,NaN,NaN

### 3. Change the column label "NAME_EDUCATION_TYPE" to "EDUCATION_TYPE"

In [37]:
# Let's check for the various head
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,NAME_EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
0,267142,0,Cash loans,F,49500.0,473760.0,Secondary / secondary special,-23768,NaN,XNA
1,344230,0,Revolving loans,F,103500.0,180000.0,Incomplete higher,-10346,Core staff,Business Entity Type 3
2,205422,0,Cash loans,M,202500.0,904608.0,Secondary / secondary special,-19321,Drivers,Self-employed
3,103524,0,Cash loans,M,112500.0,220500.0,Secondary / secondary special,-14489,Laborers,Other
4,196457,0,Cash loans,M,112500.0,454500.0,Secondary / secondary special,-10423,NaN,Mobile

In [38]:
df=df.rename(columns={"NAME_EDUCATION_TYPE": "EDUCATION_TYPE"})
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
0,267142,0,Cash loans,F,49500.0,473760.0,Secondary / secondary special,-23768,NaN,XNA
1,344230,0,Revolving loans,F,103500.0,180000.0,Incomplete higher,-10346,Core staff,Business Entity Type 3
2,205422,0,Cash loans,M,202500.0,904608.0,Secondary / secondary special,-19321,Drivers,Self-employed
3,103524,0,Cash loans,M,112500.0,220500.0,Secondary / secondary special,-14489,Laborers,Other
4,196457,0,Cash loans,M,112500.0,454500.0,Secondary / secondary special,-10423,NaN,Mobile
...,...,...,...,...,...,...,...,...,...,...
1995,442960,0,Cash loans,M,292500.0,1339884.0,Incomplete higher,-12627,Laborers,Business Entity Type 3
1996,318936,0,Cash loans,F,135000.0,111384.0,Secondary / secondary special,-17056,Laborers,Self-employed
1997,152503,0,Cash loans,M,112500.0,225000.0,Secondary / secondary special,-19457,Core staff,School
1998,285438,0,Cash loans,M,180000.0,640080.0,Secondary / secondary special,-10887,Laborers,Self-employed
1999,189812,0,Cash loans,F,450000.0,1288350.0,Secondary / secondary special,-21893,NaN,XNA

### 4. Set the index of the dataframe to "SK_ID_CURR"

In [39]:
df=df.set_index("SK_ID_CURR")

In [40]:
df

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
267142,0,Cash loans,F,49500.0,473760.0,Secondary / secondary special,-23768,NaN,XNA
344230,0,Revolving loans,F,103500.0,180000.0,Incomplete higher,-10346,Core staff,Business Entity Type 3
205422,0,Cash loans,M,202500.0,904608.0,Secondary / secondary special,-19321,Drivers,Self-employed
103524,0,Cash loans,M,112500.0,220500.0,Secondary / secondary special,-14489,Laborers,Other
196457,0,Cash loans,M,112500.0,454500.0,Secondary / secondary special,-10423,NaN,Mobile
...,...,...,...,...,...,...,...,...,...
442960,0,Cash loans,M,292500.0,1339884.0,Incomplete higher,-12627,Laborers,Business Entity Type 3
318936,0,Cash loans,F,135000.0,111384.0,Secondary / secondary special,-17056,Laborers,Self-employed
152503,0,Cash loans,M,112500.0,225000.0,Secondary / secondary special,-19457,Core staff,School
285438,0,Cash loans,M,180000.0,640080.0,Secondary / secondary special,-10887,Laborers,Self-employed
189812,0,Cash loans,F,450000.0,1288350.0,Secondary / secondary special,-21893,NaN,XNA

### 5. Get a dataframe (df2) with EDUCATION_TYPE as "Lower secondary"

In [41]:
condition = (df['EDUCATION_TYPE']=='Lower secondary')
df2=df[condition]
df2

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
148747,0,Cash loans,F,121500.0,729792.0,Lower secondary,-22755,NaN,XNA
427522,0,Cash loans,F,112500.0,152820.0,Lower secondary,-23797,NaN,XNA
261051,0,Cash loans,F,157500.0,412614.0,Lower secondary,-12516,NaN,Business Entity Type 1
434171,0,Cash loans,F,58500.0,101880.0,Lower secondary,-13352,Medicine staff,Medicine
449171,0,Cash loans,M,135000.0,503676.0,Lower secondary,-10204,Drivers,Other
119037,0,Cash loans,M,135000.0,453514.5,Lower secondary,-9319,Sales staff,Trade: type 7
332251,0,Cash loans,M,94500.0,755190.0,Lower secondary,-21589,NaN,XNA
209586,1,Revolving loans,F,45000.0,135000.0,Lower secondary,-9847,Laborers,Business Entity Type 3
158688,0,Cash loans,F,112500.0,314055.0,Lower secondary,-13625,Cooking staff,Hotel
271130,0,Cash loans,M,157500.0,582804.0,Lower secondary,-11871,Low-skill Laborers,Self-employed
215165,0,Cash loans,M,135000.0,545040.0,Lower secondary,-9800,Drivers,Business Entity Type 3
232490,0,Cash loans,F,180000.0,416052.0,Lower secondary,-15875,Laborers,Military
161795,0,Cash loans,M,247500.0,402696.0,Lower secondary,-20950,Laborers,Construction
342404,0,Cash loans,F,81000.0,269550.0,Lower secondary,-13050,Medicine staff,Kindergarten
248814,0,Cash loans,M,292500.0,254700.0,Lower secondary,-11137,Drivers,Other
197898,0,Cash loans,M,472500.0,1902672.0,Lower secondary,-17908,Drivers,Transport: type 4
238778,0,Cash loans,M,157500.0,339723.0,Lower secondary,-10173,Laborers,Industry: type 5
389876,0,Cash loans,M,135000.0,284400.0,Lower secondary,-11343,Laborers,Business Entity Type 3
414155,1,Cash loans,F,157500.0,373140.0,Lower secondary,-24466,NaN,XNA
152400,0,Cash loans,M,90000.0,508500.0,Lower secondary,-21912,NaN,XNA
335789,0,Cash loans,F,135000.0,1345500.0,Lower secondary,-10118,Sales staff,Trade: type 7
130372,0,Cash loans,M,72000.0,292500.0,Lower secondary,-14642,Laborers,Business Entity Type 2

### 6. Get a dataframe (df2) with the applicants whose OCCUPATION_TYPE is not "Managers"

In [42]:
cond2 = (df['OCCUPATION_TYPE']!='Managers')
df2=df2[cond2]
df2

<ipython-input-42-bf90f926de28>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2=df2[cond2]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
148747,0,Cash loans,F,121500.0,729792.0,Lower secondary,-22755,NaN,XNA
427522,0,Cash loans,F,112500.0,152820.0,Lower secondary,-23797,NaN,XNA
261051,0,Cash loans,F,157500.0,412614.0,Lower secondary,-12516,NaN,Business Entity Type 1
434171,0,Cash loans,F,58500.0,101880.0,Lower secondary,-13352,Medicine staff,Medicine
449171,0,Cash loans,M,135000.0,503676.0,Lower secondary,-10204,Drivers,Other
119037,0,Cash loans,M,135000.0,453514.5,Lower secondary,-9319,Sales staff,Trade: type 7
332251,0,Cash loans,M,94500.0,755190.0,Lower secondary,-21589,NaN,XNA
209586,1,Revolving loans,F,45000.0,135000.0,Lower secondary,-9847,Laborers,Business Entity Type 3
158688,0,Cash loans,F,112500.0,314055.0,Lower secondary,-13625,Cooking staff,Hotel
271130,0,Cash loans,M,157500.0,582804.0,Lower secondary,-11871,Low-skill Laborers,Self-employed
215165,0,Cash loans,M,135000.0,545040.0,Lower secondary,-9800,Drivers,Business Entity Type 3
232490,0,Cash loans,F,180000.0,416052.0,Lower secondary,-15875,Laborers,Military
161795,0,Cash loans,M,247500.0,402696.0,Lower secondary,-20950,Laborers,Construction
342404,0,Cash loans,F,81000.0,269550.0,Lower secondary,-13050,Medicine staff,Kindergarten
248814,0,Cash loans,M,292500.0,254700.0,Lower secondary,-11137,Drivers,Other
197898,0,Cash loans,M,472500.0,1902672.0,Lower secondary,-17908,Drivers,Transport: type 4
238778,0,Cash loans,M,157500.0,339723.0,Lower secondary,-10173,Laborers,Industry: type 5
389876,0,Cash loans,M,135000.0,284400.0,Lower secondary,-11343,Laborers,Business Entity Type 3
414155,1,Cash loans,F,157500.0,373140.0,Lower secondary,-24466,NaN,XNA
152400,0,Cash loans,M,90000.0,508500.0,Lower secondary,-21912,NaN,XNA
335789,0,Cash loans,F,135000.0,1345500.0,Lower secondary,-10118,Sales staff,Trade: type 7
130372,0,Cash loans,M,72000.0,292500.0,Lower secondary,-14642,Laborers,Business Entity Type 2

### 7. Get a dataframe (df2) with EDUCATION_TYPE as either "Lower secondary" or "Secondary / secondary special"

In [43]:
cond3 = (df2["EDUCATION_TYPE"].isin(["Lower secondary", "Secondary / secondary special"]))
df2=df2[cond3]
df2

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
148747,0,Cash loans,F,121500.0,729792.0,Lower secondary,-22755,NaN,XNA
427522,0,Cash loans,F,112500.0,152820.0,Lower secondary,-23797,NaN,XNA
261051,0,Cash loans,F,157500.0,412614.0,Lower secondary,-12516,NaN,Business Entity Type 1
434171,0,Cash loans,F,58500.0,101880.0,Lower secondary,-13352,Medicine staff,Medicine
449171,0,Cash loans,M,135000.0,503676.0,Lower secondary,-10204,Drivers,Other
119037,0,Cash loans,M,135000.0,453514.5,Lower secondary,-9319,Sales staff,Trade: type 7
332251,0,Cash loans,M,94500.0,755190.0,Lower secondary,-21589,NaN,XNA
209586,1,Revolving loans,F,45000.0,135000.0,Lower secondary,-9847,Laborers,Business Entity Type 3
158688,0,Cash loans,F,112500.0,314055.0,Lower secondary,-13625,Cooking staff,Hotel
271130,0,Cash loans,M,157500.0,582804.0,Lower secondary,-11871,Low-skill Laborers,Self-employed
215165,0,Cash loans,M,135000.0,545040.0,Lower secondary,-9800,Drivers,Business Entity Type 3
232490,0,Cash loans,F,180000.0,416052.0,Lower secondary,-15875,Laborers,Military
161795,0,Cash loans,M,247500.0,402696.0,Lower secondary,-20950,Laborers,Construction
342404,0,Cash loans,F,81000.0,269550.0,Lower secondary,-13050,Medicine staff,Kindergarten
248814,0,Cash loans,M,292500.0,254700.0,Lower secondary,-11137,Drivers,Other
197898,0,Cash loans,M,472500.0,1902672.0,Lower secondary,-17908,Drivers,Transport: type 4
238778,0,Cash loans,M,157500.0,339723.0,Lower secondary,-10173,Laborers,Industry: type 5
389876,0,Cash loans,M,135000.0,284400.0,Lower secondary,-11343,Laborers,Business Entity Type 3
414155,1,Cash loans,F,157500.0,373140.0,Lower secondary,-24466,NaN,XNA
152400,0,Cash loans,M,90000.0,508500.0,Lower secondary,-21912,NaN,XNA
335789,0,Cash loans,F,135000.0,1345500.0,Lower secondary,-10118,Sales staff,Trade: type 7
130372,0,Cash loans,M,72000.0,292500.0,Lower secondary,-14642,Laborers,Business Entity Type 2

### 8. Get a dataframe (df2) with the applicant with AMT_INCOME_TOTAL between 100K and 200K (included)

In [44]:
df2["AMT_INCOME_TOTAL"].astype(float)
cond4 = (df2["AMT_INCOME_TOTAL"] >= 100000) & (df2["AMT_INCOME_TOTAL"] <= 200000)
df2 [cond4]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
148747,0,Cash loans,F,121500.0,729792.0,Lower secondary,-22755,NaN,XNA
427522,0,Cash loans,F,112500.0,152820.0,Lower secondary,-23797,NaN,XNA
261051,0,Cash loans,F,157500.0,412614.0,Lower secondary,-12516,NaN,Business Entity Type 1
449171,0,Cash loans,M,135000.0,503676.0,Lower secondary,-10204,Drivers,Other
119037,0,Cash loans,M,135000.0,453514.5,Lower secondary,-9319,Sales staff,Trade: type 7
158688,0,Cash loans,F,112500.0,314055.0,Lower secondary,-13625,Cooking staff,Hotel
271130,0,Cash loans,M,157500.0,582804.0,Lower secondary,-11871,Low-skill Laborers,Self-employed
215165,0,Cash loans,M,135000.0,545040.0,Lower secondary,-9800,Drivers,Business Entity Type 3
232490,0,Cash loans,F,180000.0,416052.0,Lower secondary,-15875,Laborers,Military
238778,0,Cash loans,M,157500.0,339723.0,Lower secondary,-10173,Laborers,Industry: type 5
389876,0,Cash loans,M,135000.0,284400.0,Lower secondary,-11343,Laborers,Business Entity Type 3
414155,1,Cash loans,F,157500.0,373140.0,Lower secondary,-24466,NaN,XNA
335789,0,Cash loans,F,135000.0,1345500.0,Lower secondary,-10118,Sales staff,Trade: type 7

### 9. Get a dataframe (df2) with only male applicants with AMT_INCOME_TOTAL less than 100K (included)

In [49]:
df2["AMT_INCOME_TOTAL"].astype(float)
cond5 = (df2['CODE_GENDER']=='M') & (df2['AMT_INCOME_TOTAL']<=100000)
df2[cond5]

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT,EDUCATION_TYPE,DAYS_BIRTH,OCCUPATION_TYPE,ORGANIZATION_TYPE
SK_ID_CURR,,,,,,,,,
332251,0,Cash loans,M,94500.0,755190.0,Lower secondary,-21589,NaN,XNA
152400,0,Cash loans,M,90000.0,508500.0,Lower secondary,-21912,NaN,XNA
130372,0,Cash loans,M,72000.0,292500.0,Lower secondary,-14642,Laborers,Business Entity Type 2

### 10. Get a dataframe (df2) with three columns (SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE) and only the applications for "Cash loans"

In [62]:
df2=df[['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE']]
cond6=(df2["NAME_CONTRACT_TYPE"]=="Cash loans")
df2_filt=df2[cond6]
df2_filt

      SK_ID_CURR  TARGET NAME_CONTRACT_TYPE
0         267142       0         Cash loans
2         205422       0         Cash loans
3         103524       0         Cash loans
4         196457       0         Cash loans
5         399761       0         Cash loans
...          ...     ...                ...
1995      442960       0         Cash loans
1996      318936       0         Cash loans
1997      152503       0         Cash loans
1998      285438       0         Cash loans
1999      189812       0         Cash loans

[1810 rows x 3 columns]